name: NoChatReports
version: '${project.version}'
main: we.hate.chatreports.NoChatReports
api-version: 1.19
authors: [ TechnicallyCoded ]
description: "Prevent message signatures from being sent to clients"
website: "https://tcoded.com"
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
